name: build-n-deploy

on:
  push:
    paths:
      - 'client/**'
      - 'director-*/**'
      - 'storage/**'
      - 'webui/**'
      - '.github/actions/**'
      - '.github/workflows/*.yml'
    branches:
      - master
      - ci_optim
  pull_request:
    paths:
      - 'client/**'
      - 'director-*/**'
      - 'storage/**'
      - 'webui/**'
      - '.github/actions/**'
      - '.github/workflows/*.yml'
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [client, director, storage, webui]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare build file
        uses: ./.github/actions/prepare-bareos-build
        with:
          bareos_app: ${{ matrix.module }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact-${{ matrix.module }}
          path: build

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [client, director, storage, webui]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build-artifact-${{ matrix.module }}
          path: build

      - name: Build images
        uses: ./.github/actions/build-bareos-app
        with:
          bareos_app: ${{ matrix.module }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact-${{ matrix.module }}
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [client, director, storage, webui]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build-artifact-${{ matrix.module }}
          path: build

      - name: Load and push images
        uses: ./.github/actions/push-bareos-app
        with:
          docker_pass: ${{ secrets.DOCKER_PASS }}
          bareos_app: ${{ matrix.module }}
